### ISSUE TITLE
Disabling leading zero also disables leading one

### ISSUE THREAD

**Issue by stpgod** [eamodio/fitbit-pure#1]
When the leading zero is disabled, hours beginning with 1 do not display properly. Love the clean and simple look, but 10:34 turned into 0:34 with the leading zero turned off.

If you're able to patch that it would be awesome!

**Comment by stpgod** [comment]
Using a Versa 2, connected to a Pixel 3
![Screenshot_20191226-225138](https://user-images.githubusercontent.com/5177029/71505630-c235c100-2832-11ea-9c54-79bc3e894e68.png)

**Comment by eamodio** [comment]
Thanks for the report! I've fixed this and a bunch of other small issues, but unfortunately, it seems to be taking a while for Fitbit to review my latest update (it's been well over a week now). Hopefully it will be out soon.
